name = "remix-duckdb-wasm"
main = "./build/server/index.js"
compatibility_date = "2023-09-22"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[build]
command = "bun run build"

[env.production]
route = ""
vars = { NODE_ENV = "production" }

[env.development]
vars = { NODE_ENV = "development" }
